# This tells GitHub what to use 
title: "Justin X. Hale's Portfolio"
description: "A UX Designer specializing in CLI and developer tools"
remote_theme: "just-the-docs/just-the-docs"

# Enable navigation
permalink: pretty

include:
  - portfolio/rapid-design-thinking/assets

# Aux links for the upper right navigation
aux_links:
  "Justin X. Hale GitHub Repo":
    - "//github.com/justinxhale"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true