# Site basics
title: "Justin X. Hale's Portfolio"
description: "A UX Designer specializing in CLI and developer tools"
remote_theme: "just-the-docs/just-the-docs"

# IMPORTANT for project pages (your repo is not a user/org site)
url: "https://justinxhale.github.io"
baseurl: ""

# Look & feel (optional)
logo: "/assets/icon-512.png"     # optional; appears in the header
favicon_ico: "/assets/icon-512.png"

# Navigation / behavior
permalink: pretty
aux_links_new_tab: true

# Back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Footer links (optional)
just_the_docs:
  footer:
    links:
      - text: "Privacy Policy"
        url: "/privacy-policy/"
      - text: "Support"
        url: "/support/"

# Plugins
plugins:
  - jekyll-github-metadata
