# This tells GitHub what to use 
title: "Justin X. Hale's Portfolio"
description: "A UX Designer specializing in CLI and developer tools"
remote_theme: "just-the-docs/just-the-docs"

# Enable navigation
permalink: pretty

include:
  - portfolio/rapid-design-thinking/assets

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Generate footer
just_the_docs:
  footer:
    links:
      - text: "Privacy Policy"
        url: "/privacy-policy/"
