# This tells GitHub what to use 
title: "Justin X. Hale's Portfolio"
description: "A UX Designer specializing in CLI and developer tools"
remote_theme: "just-the-docs/just-the-docs"

# Enable navigation
permalink: pretty

include:
  - portfolio/rapid-design-thinking/assets

